apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: niffler-st5-frontend
  namespace: niffler-st5
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: niffler-st5.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: niffler-st5-frontend
                port:
                  number: 80